version: "3"

services:
  aapanel:
    build:
      context: .
    container_name: "aapanel-webserver"
    ports:
      - "${AAPANEL_PORT}:7800"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
      - "${REDIS_PORT}:6379"
    volumes:
      - ${WEBSITE_DATA}:/www/wwwroot
      - ${WEBSITE_LOG}:/www/wwwlogs
